replicaCount: 2

image:
  repository: 232428702881.dkr.ecr.ap-south-1.amazonaws.com/k8s-gitops-service-b
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

environment:
  SERVICE_NAME: service-b
